# Generated by Django 6.0.6 on 2026-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorapp', '0002_remove_donor_age_remove_donor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='lastDonated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
